//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyTitle("GroupCacheStubTest")]
[assembly: System.Reflection.AssemblyVersion("7.07.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("7.07.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

